name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore AtlasToolbox\AtlasToolbox.csproj

    - name: Build and Publish Application
      run: dotnet publish AtlasToolbox\AtlasToolbox.csproj -c Release -p:Platform=x64 -r win-x64 --self-contained true -o "${{ github.workspace }}\Deploy\src\"

    - name: Compile .ISS to .EXE Installer
      uses: robin24/inno-setup-action@v1
      with:
        filepath: "${{ github.workspace }}\Installer\setup.iss"

    - name: Create ZIP of MSI
      run: powershell Compress-Archive -Path "${{ github.workspace }}\Installer\Output\*" -DestinationPath "${{ github.workspace }}\AtlasToolbox-Installer.zip"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AtlasToolbox-Installer
        path: "${{ github.workspace }}\AtlasToolbox-Installer.zip"
